ad=input("Adınız: ")
sad=input("Soy Adınız: ")
y = int(input("Yaşınız: "))
dy = input("Doğum Yeriniz: ")
dt = input("Doğum Tarhiniz:")
print("")
print("")
print("")
print("")
print("="*10)
print("Ad               :"+ad)
print("SoyAd            :"+sad)
print("Yaş              :"+str(y))
print("Doğum Yeri       :"+dy)
print("Doğum Tarihi     :"+dt)
print("="*10)